// Killer7
// #ID = 7032

// ======================================================================= //
// Progression Achievement Definitions
// ======================================================================= //

achievement(
    title = "[Draft] Collect the Fire Ring", points = 5,
    description = "While playing Target 00 [Angel], collect the Fire Ring in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Vinculum Speed Smile", points = 5,
    description = "While playing Target 00 [Angel], enter the Vinculum Gate and defeat the Speed Smile in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 00 [Angel] on Normal", points = 5,
    description = "Complete Target 00 [Angel] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 00 [Angel] on Deadly", points = 10,
    description = "Complete Target 00 [Angel] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Collect the Water Ring", points = 5,
    description = "While playing Target 01 Part 01 [Sunset], collect the Water Ring in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Vinculum Phantom Smile", points = 5,
    description = "While playing Target 01 Part 01 [Sunset], enter the Vinculum Gate and defeat the Phantom Smile in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Collect the Wind Ring", points = 5,
    description = "While playing Target 01 Part 01 [Sunset], collect the Wind Ring in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 01 [Sunset] on Normal", points = 5,
    description = "Complete Target 01 [Sunset] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 01 [Sunset] on Deadly", points = 10,
    description = "Complete Target 01 [Sunset] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Collect the Stamina Ring", points = 5,
    description = "While playing Target 02 [Cloudman], collect the Stamina Ring in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Collect the Ulmeyda Figures", points = 5,
    description = "While playing Target 02 [Cloudman], collect all of the Ulmeyda Figures in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 02 [Cloudman] on Normal", points = 5,
    description = "Complete Target 02 [Cloudman] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 02 [Cloudman] on Deadly", points = 10,
    description = "Complete Target 02 [Cloudman] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Collect the Time Ring", points = 5,
    description = "While playing Target 03 Part 01 [Encounter], collect the Time Ring in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Vinculum Mithril Smile", points = 5,
    description = "While playing Target 03 Part 01 [Encounter], enter the Vinculum Gate and defeat the Mithril Smile in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Collect the Power Ring", points = 5,
    description = "While playing Target 03 Part 02 [Encounter], collect the Power Ring in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Vinculum Laser Smile", points = 5,
    description = "While playing Target 03 Part 02 [Encounter], enter the Vinculum Gate and defeat the Laser Smile in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 03 [Encounter] on Normal", points = 5,
    description = "Complete Target 03 [Encounter] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 03 [Encounter] on Deadly", points = 10,
    description = "Complete Target 03 [Encounter] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Collect the Punishing Rangers Color Samples", points = 5,
    description = "While playing Target 04 Part 01 [Cloudman], collect all of the Punishing Rangers Color Samples in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 04 [Alter Ego] on Normal", points = 5,
    description = "Complete Target 04 [Alter Ego] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 04 [Alter Ego] on Deadly", points = 10,
    description = "Complete Target 04 [Alter Ego] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Vinculum Timer Smile", points = 5,
    description = "While playing Target 05 Part 01 [Smile], enter the Vinculum Gate and defeat the Timer Smile in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Collect the Holbert's Cassettes", points = 5,
    description = "While playing Target 05 Part 02 [Smile], collect all of the Holbert's Cassettes in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Vinculum Galactic Tomahawk Smile", points = 5,
    description = "While playing Target 05 Part 02 [Smile], enter the Vinculum Gate and defeat the Galactic Tomahawk Smile in any mode and on any difficulty",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 05 [Smile] on Normal", points = 5,
    description = "Complete Target 05 [Smile] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "progression"
)
achievement(
    title = "[Draft] Complete Target 05 [Smile] on Deadly", points = 10,
    description = "Complete Target 05 [Smile] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] After defying Matsuken, complete Target 06 [Lion] on Normal", points = 10,
    description = "Complete Target 06 [Lion] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "win_condition"
)
achievement(
    title = "[Draft] After siding with Matsuken, complete Target 06 [Lion] on Normal", points = 10,
    description = "Complete Target 06 [Lion] in Killer7 mode and on Normal difficulty or higher",
    trigger = always_false(),
    type = "win_condition"
)
achievement(
    title = "[Draft] After defying Matsuken, complete Target 06 [Lion] on Deadly", points = 25,
    description = "Complete Target 06 [Lion] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] After siding with Matsuken, complete Target 06 [Lion] on Deadly", points = 25,
    description = "Complete Target 06 [Lion] in Killer7 mode and on Deadly difficulty",
    trigger = always_false()
)

// ======================================================================= //
// Action/Boss Challenge Achievement Definitions
// ======================================================================= //

achievement(
    title = "[Draft] No Miss Kill Combo", points = 10,
    description = "Reach a Kill Combo of 7 or more without missing, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Kill Combo", points = 10,
    description = "Maintain a Kill Combo of 28 or more, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] 77 Smiles", points = 5,
    description = "Kill 77 Smiles or more in any single assignment, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] 154 Smiles", points = 10,
    description = "Kill 154 Smiles or more in any single assignment, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Miss Angel", points = 10,
    description = "While playing Target 00 [Angel], defeat Angel without missing a shot, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] 140 Hit Julia Kisugi", points = 10,
    description = "While playing Target 01 Part 01 [Sunset], defeat Julia Kisugi by scoring 140 or more hits, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] One Shot Jean DePaul", points = 10,
    description = "While playing Target 01 Part 02 [Sunset], defeat Jean DePaul with one shot, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Minimum Shots Kurahashi & Akiba", points = 25,
    description = "While playing Target 01 Part 02 [Sunset], defeat Kurahashi & Akiba without firing more than 14 shots, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Speed Kill Andrei Ulmeyda", points = 10,
    description = "While playing Target 02 [Cloudman], defeat Andrei Ulmeyda in 77 seconds or less, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Miss Ayame Blackburn 1", points = 25,
    description = "While playing Target 03 Part 01 [Encounter], defeat Ayame Blackburn without missing a shot, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Damage Ayame Blackburn 2", points = 50,
    description = "While playing Target 03 Part 02 [Encounter], defeat Ayame Blackburn without taking damage, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Shot Curtis Blackburn", points = 10,
    description = "While playing Target 03 Part 02 [Encounter], defeat Curtis Blackburn without letting him get a shot off, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Minimum Shots Greg Nightmare", points = 25,
    description = "While playing Target 05 Part 02 [Smile], defeat Greg Nightmare without firing more than 21 shots, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Camellia Smile Kill", points = 10,
    description = "Kill a Camellia Smile by shooting its weakpoint and gain an excess of Thin Blood, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Yellow Micro Smile Kill", points = 5,
    description = "Kill a yellow Micro Smile and restore your health, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Red Micro Smile Kill", points = 5,
    description = "Kill a red Micro Smile and gain an excess of Thin Blood, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Broken Smile Kill", points = 50,
    description = "Kill a Broken Smile by shooting the weakpoint on its jetpack, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Giant Smile Kill", points = 25,
    description = "Kill a Giant Smile by shooting its eye, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Laser Smile Kill", points = 10,
    description = "Kill a Laser Smile by shooting its weakpoint, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Death Target 00", points = 10,
    description = "Complete Target 00 [Angel] without losing a Smith, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Death Target 01", points = 10,
    description = "Complete Target 01 [Sunset] without losing a Smith, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Death Target 02", points = 10,
    description = "Complete Target 02 [Cloudman] without losing a Smith, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Death Target 03", points = 10,
    description = "Complete Target 03 [Encounter] without losing a Smith, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Death Target 04", points = 10,
    description = "Complete Target 04 [Alter Ego] without losing a Smith, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] No Death Target 05", points = 25,
    description = "Complete Target 05 [Alter Ego] without losing a Smith, in any mode and on any difficulty",
    trigger = always_false()
)

// ======================================================================= //
// Post Game Challenge Achievement Definitions
// ======================================================================= //

achievement(
    title = "[Draft] Complete Target 00 [Angel] on Killer8 Mode", points = 10,
    description = "Complete Target 00 [Angel] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Complete Target 01 [Sunset] on Killer8 Mode", points = 10,
    description = "Complete Target 01 [Sunset] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Complete Target 02 [Cloudman] on Killer8 Mode", points = 10,
    description = "Complete Target 02 [Cloudman] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Complete Target 03 [Encounter] on Killer8 Mode", points = 10,
    description = "Complete Target 03 [Encounter] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Complete Target 04 [Alter Ego] on Killer8 Mode", points = 10,
    description = "Complete Target 04 [Alter Ego] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Complete Target 05 [Smile] on Killer8 Mode", points = 10,
    description = "Complete Target 05 [Smile] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Complete Target 06 [Lion] on Killer8 Mode", points = 10,
    description = "Complete Target 06 [Lion] on Killer8 mode",
    trigger = always_false()
)
achievement(
    title = "[Draft] Upgrade All Skills", points = 10,
    description = "Upgrade all skills for any Smith, in any mode and on any difficulty",
    trigger = always_false()
)

// ======================================================================= //
// Other Challenge Achievement Definitions
// ======================================================================= //

achievement(
    title = "[Draft] Pigeon Collector", points = 5,
    description = "Collect all Carrier Pigeons, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Angel]", points = 5,
    description = "While playing Target 00 [Angel], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Sunset 1]", points = 5,
    description = "While playing Target 01 Part 01 [Sunset], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Sunset 2]", points = 5,
    description = "While playing Target 01 Part 02 [Sunset], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Cloudman]", points = 5,
    description = "While playing Target 02 [Cloudman], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Encounter 1]", points = 5,
    description = "While playing Target 03 Part 01 [Encounter], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Encounter 2]", points = 5,
    description = "While playing Target 03 Part 02 [Encounter], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Alter Ego]", points = 5,
    description = "While playing Target 04 Part 01 [Angel], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Break the Bank [Smile 1]", points = 10,
    description = "While playing Target 05 Part 01 [Smile], break the Blood Room blood tank, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] 1000dl of Blood", points = 4,
    description = "Hold 1000dl of Thin Blood any any one time, in any mode and on any difficulty",
    trigger = always_false()
)
achievement(
    title = "[Draft] Wake up a Smith", points = 3,
    description = "Wake up a sleep Smith in any single assignment, in any mode and on any difficulty",
    trigger = always_false()
)